services:
  - type: web
    name: upscaloro-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: False
      - key: CORS_ORIGINS
        value: https://upscaloro.vercel.app,https://*.vercel.app
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health 